# Generated by Django 4.2.3 on 2023-10-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoDetails',
        ),
    ]
