# Generated by Django 4.2.3 on 2023-10-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catogory_anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('small_image', models.ImageField(upload_to='images')),
                ('big_image', models.ImageField(upload_to='bigimages')),
                ('video_file', models.FileField(upload_to='video')),
                ('slug', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Catogory_movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('small_image', models.ImageField(upload_to='images')),
                ('big_image', models.ImageField(upload_to='bigimages')),
                ('video_file', models.FileField(upload_to='video')),
                ('slug', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Catogory_new_release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('small_image', models.ImageField(upload_to='images')),
                ('big_image', models.ImageField(upload_to='bigimages')),
                ('video_file', models.FileField(upload_to='video')),
                ('slug', models.CharField(max_length=130)),
            ],
        ),
    ]
