# Generated by Django 4.2.3 on 2023-10-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_catogory_anime_big_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user_image',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='user_age',
            field=models.IntegerField(default=15),
        ),
    ]
