# Generated by Django 4.2.3 on 2023-10-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='category',
            field=models.CharField(choices=[('All', 'Everything'), ('A', 'Anime'), ('H', 'Hollywood'), ('K', 'korean Drama'), ('AC', 'Action'), ('S', 'sad'), ('M', 'Mature')], default='All', max_length=25),
        ),
    ]
