# Generated by Django 4.2.3 on 2023-10-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_userdetails_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='category',
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('All', 'Everything'), ('A', 'Anime'), ('H', 'Hollywood'), ('K', 'korean Drama'), ('AC', 'Action'), ('S', 'sad'), ('M', 'Mature')], default='All', max_length=25),
        ),
    ]
