# Generated by Django 4.2.3 on 2023-10-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_userdetails_category_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_choice',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
