# Generated by Django 4.2.3 on 2023-10-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_userdetails_user_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_choice',
            field=models.CharField(default='All', max_length=30),
        ),
    ]
