# Generated by Django 4.2.3 on 2023-10-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_userdetails_user_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user_choice',
        ),
    ]
