# Generated by Django 4.2.3 on 2023-10-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_usermovieinteraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMovieInteraction',
        ),
    ]
