# Generated by Django 4.2.3 on 2023-10-22 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_userdetails_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user_image',
        ),
    ]
