# Generated by Django 4.2.3 on 2023-10-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_userdetails_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='profileimages'),
        ),
    ]
